/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataKegiatan(tabelKegiatan, "SELECT*FROM kegiatan");
        mycode.tampilDataDaftarUkm(tabelUkm, "SELECT*FROM daftar_ukm");
        mycode.tampilDataPengurus(tabelPengurus, "SELECT*FROM pengurus");
        mycode.tampilDataDaftarProduk(tabelDaftarProduk, "SELECT*FROM daftar_produk");
        mycode.tampilDataKomentar(tabelKomentar, "SELECT*FROM komentar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlProduk = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        txtIdUkmProduk = new javax.swing.JTextField();
        btnHpsProduk = new javax.swing.JButton();
        btnSmpnProduk = new javax.swing.JButton();
        btnUbhProduk = new javax.swing.JButton();
        txtCariDaftarProduk = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelDaftarProduk = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        txtIdProduk = new javax.swing.JTextField();
        pnlUkm = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAlamatUkm = new javax.swing.JTextField();
        txtNamaUkm = new javax.swing.JTextField();
        txtJenisUsaha = new javax.swing.JTextField();
        btnHpsDaftarUkm = new javax.swing.JButton();
        btnSmpnDaftarUkm = new javax.swing.JButton();
        btnUbhDaftarUkm = new javax.swing.JButton();
        txtCariDaftarUkm = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelUkm = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdUkm = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtNomorUkm = new javax.swing.JTextField();
        txtKecamatan = new javax.swing.JTextField();
        txtInfoUkm = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtTahunBerdiri = new javax.swing.JTextField();
        txtLokasiUkm = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        pnlKegiatan = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTanggalKegiatan = new javax.swing.JTextField();
        txtNamaKegiatan = new javax.swing.JTextField();
        txtTempatKegiatan = new javax.swing.JTextField();
        btnHpsKegiatan = new javax.swing.JButton();
        btnSmpnKegiatan = new javax.swing.JButton();
        btnUbhKegiatan = new javax.swing.JButton();
        txtCariKegiatan = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelKegiatan = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdKegiatan = new javax.swing.JTextField();
        pnlKomentar = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtReplyFrom = new javax.swing.JTextField();
        txtIdUkmKomen = new javax.swing.JTextField();
        txtTanggalKomen = new javax.swing.JTextField();
        btnHpsKomentar = new javax.swing.JButton();
        btnSmpnKomentar = new javax.swing.JButton();
        btnUbhKomentar = new javax.swing.JButton();
        txtCariKomentar = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelKomentar = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtIdKomen = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtIsiKomen = new javax.swing.JTextField();
        txtEmailKomen = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtNamaKomen = new javax.swing.JTextField();
        pnlPengurus = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JTextField();
        txtNamaPengurus = new javax.swing.JTextField();
        btnHpsPengurus = new javax.swing.JButton();
        btnSmpnPengurus = new javax.swing.JButton();
        btnUbhPengurus = new javax.swing.JButton();
        txtCariPengurus = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelPengurus = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtIdPengurus = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnProduk = new javax.swing.JButton();
        btnUkm = new javax.swing.JButton();
        btnKegiatan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnKomentar = new javax.swing.JButton();
        btnPengurus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlProduk.setBackground(new java.awt.Color(0, 255, 204));
        pnlProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Nama Produk");
        pnlProduk.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("ID UKM");
        pnlProduk.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNamaProduk.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaProduk.setForeground(new java.awt.Color(0, 0, 0));
        pnlProduk.add(txtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdUkmProduk.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUkmProduk.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUkmProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUkmProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(txtIdUkmProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsProduk.setText("HAPUS");
        btnHpsProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnHpsProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnProduk.setText("SIMPAN");
        btnSmpnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnSmpnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, -1));

        btnUbhProduk.setText("UBAH");
        btnUbhProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(btnUbhProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariDaftarProduk.setBackground(new java.awt.Color(255, 255, 255));
        txtCariDaftarProduk.setForeground(new java.awt.Color(0, 0, 0));
        txtCariDaftarProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDaftarProdukKeyReleased(evt);
            }
        });
        pnlProduk.add(txtCariDaftarProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, -1));

        tabelDaftarProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabelDaftarProduk);

        pnlProduk.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 480, 155));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("ID Produk");
        pnlProduk.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdProduk.setBackground(new java.awt.Color(255, 255, 255));
        txtIdProduk.setForeground(new java.awt.Color(0, 0, 0));
        txtIdProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdukActionPerformed(evt);
            }
        });
        pnlProduk.add(txtIdProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlProduk, "card4");

        pnlUkm.setBackground(new java.awt.Color(0, 255, 204));
        pnlUkm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Jenis Usaha");
        pnlUkm.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 132, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Alamat ");
        pnlUkm.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nama UKM");
        pnlUkm.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtAlamatUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatUkm.setForeground(new java.awt.Color(0, 0, 0));
        pnlUkm.add(txtAlamatUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 220, -1));

        txtNamaUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaUkm.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaUkmActionPerformed(evt);
            }
        });
        pnlUkm.add(txtNamaUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 220, -1));

        txtJenisUsaha.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisUsaha.setForeground(new java.awt.Color(0, 0, 0));
        pnlUkm.add(txtJenisUsaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, -1));

        btnHpsDaftarUkm.setText("HAPUS");
        btnHpsDaftarUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsDaftarUkmActionPerformed(evt);
            }
        });
        pnlUkm.add(btnHpsDaftarUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, 30));

        btnSmpnDaftarUkm.setText("SIMPAN");
        btnSmpnDaftarUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnDaftarUkmActionPerformed(evt);
            }
        });
        pnlUkm.add(btnSmpnDaftarUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 30));

        btnUbhDaftarUkm.setText("UBAH");
        btnUbhDaftarUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhDaftarUkmActionPerformed(evt);
            }
        });
        pnlUkm.add(btnUbhDaftarUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, 30));

        txtCariDaftarUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtCariDaftarUkm.setForeground(new java.awt.Color(0, 0, 0));
        txtCariDaftarUkm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDaftarUkmKeyReleased(evt);
            }
        });
        pnlUkm.add(txtCariDaftarUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 350, -1));

        tabelUkm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelUkm);

        pnlUkm.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 750, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID UKM");
        pnlUkm.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUkm.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUkmActionPerformed(evt);
            }
        });
        pnlUkm.add(txtIdUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 220, -1));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Info ");
        pnlUkm.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 132, -1));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Nomor UKM");
        pnlUkm.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Kecamatan");
        pnlUkm.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        txtNomorUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtNomorUkm.setForeground(new java.awt.Color(0, 0, 0));
        pnlUkm.add(txtNomorUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, -1));

        txtKecamatan.setBackground(new java.awt.Color(255, 255, 255));
        txtKecamatan.setForeground(new java.awt.Color(0, 0, 0));
        txtKecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKecamatanActionPerformed(evt);
            }
        });
        pnlUkm.add(txtKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 220, -1));

        txtInfoUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtInfoUkm.setForeground(new java.awt.Color(0, 0, 0));
        pnlUkm.add(txtInfoUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 220, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Tahun Berdiri");
        pnlUkm.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        txtTahunBerdiri.setBackground(new java.awt.Color(255, 255, 255));
        txtTahunBerdiri.setForeground(new java.awt.Color(0, 0, 0));
        txtTahunBerdiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunBerdiriActionPerformed(evt);
            }
        });
        pnlUkm.add(txtTahunBerdiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 220, -1));

        txtLokasiUkm.setBackground(new java.awt.Color(255, 255, 255));
        txtLokasiUkm.setForeground(new java.awt.Color(0, 0, 0));
        pnlUkm.add(txtLokasiUkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 220, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Lokasi");
        pnlUkm.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 132, -1));

        Content.add(pnlUkm, "card4");

        pnlKegiatan.setBackground(new java.awt.Color(0, 255, 204));
        pnlKegiatan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Tempat");
        pnlKegiatan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Tanggal ");
        pnlKegiatan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Nama ");
        pnlKegiatan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtTanggalKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        pnlKegiatan.add(txtTanggalKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKegiatanActionPerformed(evt);
            }
        });
        pnlKegiatan.add(txtNamaKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTempatKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtTempatKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        pnlKegiatan.add(txtTempatKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsKegiatan.setText("HAPUS");
        btnHpsKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKegiatanActionPerformed(evt);
            }
        });
        pnlKegiatan.add(btnHpsKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnKegiatan.setText("SIMPAN");
        btnSmpnKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKegiatanActionPerformed(evt);
            }
        });
        pnlKegiatan.add(btnSmpnKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, -1));

        btnUbhKegiatan.setText("UBAH");
        btnUbhKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKegiatanActionPerformed(evt);
            }
        });
        pnlKegiatan.add(btnUbhKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKegiatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKegiatanKeyReleased(evt);
            }
        });
        pnlKegiatan.add(txtCariKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, -1));

        tabelKegiatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelKegiatan);

        pnlKegiatan.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 480, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Kegiatan");
        pnlKegiatan.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        txtIdKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKegiatanActionPerformed(evt);
            }
        });
        pnlKegiatan.add(txtIdKegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlKegiatan, "card3");

        pnlKomentar.setBackground(new java.awt.Color(0, 255, 204));
        pnlKomentar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tanggal");
        pnlKomentar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Reply From");
        pnlKomentar.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("ID UKM");
        pnlKomentar.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtReplyFrom.setBackground(new java.awt.Color(255, 255, 255));
        txtReplyFrom.setForeground(new java.awt.Color(0, 0, 0));
        pnlKomentar.add(txtReplyFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdUkmKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUkmKomen.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUkmKomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUkmKomenActionPerformed(evt);
            }
        });
        pnlKomentar.add(txtIdUkmKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTanggalKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKomen.setForeground(new java.awt.Color(0, 0, 0));
        pnlKomentar.add(txtTanggalKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));

        btnHpsKomentar.setText("HAPUS");
        btnHpsKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKomentarActionPerformed(evt);
            }
        });
        pnlKomentar.add(btnHpsKomentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnKomentar.setText("SIMPAN");
        btnSmpnKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKomentarActionPerformed(evt);
            }
        });
        pnlKomentar.add(btnSmpnKomentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, -1));

        btnUbhKomentar.setText("UBAH");
        btnUbhKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKomentarActionPerformed(evt);
            }
        });
        pnlKomentar.add(btnUbhKomentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariKomentar.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKomentar.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKomentar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKomentarKeyReleased(evt);
            }
        });
        pnlKomentar.add(txtCariKomentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelKomentar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelKomentar);

        pnlKomentar.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 480, 155));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ID Komentar");
        pnlKomentar.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKomen.setForeground(new java.awt.Color(0, 0, 0));
        txtIdKomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKomenActionPerformed(evt);
            }
        });
        pnlKomentar.add(txtIdKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Isi Komentar");
        pnlKomentar.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Email");
        pnlKomentar.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtIsiKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtIsiKomen.setForeground(new java.awt.Color(0, 0, 0));
        pnlKomentar.add(txtIsiKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        txtEmailKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailKomen.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailKomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailKomenActionPerformed(evt);
            }
        });
        pnlKomentar.add(txtEmailKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Nama");
        pnlKomentar.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtNamaKomen.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKomen.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaKomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKomenActionPerformed(evt);
            }
        });
        pnlKomentar.add(txtNamaKomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        Content.add(pnlKomentar, "card5");

        pnlPengurus.setBackground(new java.awt.Color(0, 255, 204));
        pnlPengurus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Jabatan");
        pnlPengurus.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Nama ");
        pnlPengurus.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtJabatan.setBackground(new java.awt.Color(255, 255, 255));
        txtJabatan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPengurus.add(txtJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaPengurus.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPengurus.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPengurusActionPerformed(evt);
            }
        });
        pnlPengurus.add(txtNamaPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsPengurus.setText("HAPUS");
        btnHpsPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPengurusActionPerformed(evt);
            }
        });
        pnlPengurus.add(btnHpsPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnPengurus.setText("SIMPAN");
        btnSmpnPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPengurusActionPerformed(evt);
            }
        });
        pnlPengurus.add(btnSmpnPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 80, -1));

        btnUbhPengurus.setText("UBAH");
        btnUbhPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPengurusActionPerformed(evt);
            }
        });
        pnlPengurus.add(btnUbhPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariPengurus.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPengurus.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPengurus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPengurusKeyReleased(evt);
            }
        });
        pnlPengurus.add(txtCariPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, -1));

        tabelPengurus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelPengurus);

        pnlPengurus.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 480, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ID Pengurus");
        pnlPengurus.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdPengurus.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPengurus.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPengurusActionPerformed(evt);
            }
        });
        pnlPengurus.add(txtIdPengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlPengurus, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SISTEM INFORMASI MANAJEMEN UKM PERIKANAN");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 153, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnProduk.setBackground(new java.awt.Color(0, 204, 204));
        btnProduk.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnProduk.setForeground(new java.awt.Color(0, 0, 0));
        btnProduk.setText("PRODUK");
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnUkm.setBackground(new java.awt.Color(0, 204, 204));
        btnUkm.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnUkm.setForeground(new java.awt.Color(0, 0, 0));
        btnUkm.setText("DAFTAR UKM");
        btnUkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkmActionPerformed(evt);
            }
        });

        btnKegiatan.setBackground(new java.awt.Color(0, 204, 204));
        btnKegiatan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        btnKegiatan.setText("KEGIATAN");
        btnKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKegiatanActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnKomentar.setBackground(new java.awt.Color(0, 204, 204));
        btnKomentar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKomentar.setForeground(new java.awt.Color(0, 0, 0));
        btnKomentar.setText("KOMENTAR");
        btnKomentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomentarActionPerformed(evt);
            }
        });

        btnPengurus.setBackground(new java.awt.Color(0, 204, 204));
        btnPengurus.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPengurus.setForeground(new java.awt.Color(0, 0, 0));
        btnPengurus.setText("PENGURUS");
        btnPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengurusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUkm)
                    .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKegiatan)
                    .addComponent(btnKomentar)
                    .addComponent(btnPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKegiatan, btnKomentar, btnPengurus, btnProduk, btnUkm});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUkm)
                .addGap(18, 18, 18)
                .addComponent(btnKegiatan)
                .addGap(18, 18, 18)
                .addComponent(btnKomentar)
                .addGap(18, 18, 18)
                .addComponent(btnPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKegiatan, btnKomentar, btnPengurus, btnProduk, btnUkm});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        Content.removeAll(); 
        Content.add(pnlProduk);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkmActionPerformed
        Content.removeAll(); 
        Content.add(pnlUkm);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnUkmActionPerformed

    private void btnKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKegiatanActionPerformed
        Content.removeAll(); 
        Content.add(pnlKegiatan);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKegiatanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomentarActionPerformed
        Content.removeAll(); 
        Content.add(pnlKomentar);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnKomentarActionPerformed

    private void txtCariDaftarUkmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDaftarUkmKeyReleased
        String c = txtCariDaftarUkm.getText();
        String cari = "SELECT*FROM daftar_ukm WHERE id_ukm LIKE '%"+c+"%'"+
                      "OR nama_ukm LIKE '%"+c+"%' OR alamat LIKE '%"+c+"%'"+
                      "OR jenis_usaha LIKE '%"+c+"%' OR kecamatan LIKE '%"+c+"%'"+
                      "OR nomor LIKE '%"+c+"%'";
        mycode.tampilDataDaftarUkm(tabelUkm, cari);
    }//GEN-LAST:event_txtCariDaftarUkmKeyReleased

    private void btnUbhDaftarUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhDaftarUkmActionPerformed
        try {
            mycode.ubahDaftarUkm(txtIdUkm.getText(), txtNamaUkm.getText(),
                                txtAlamatUkm.getText(), txtJenisUsaha.getText(),
                                txtTahunBerdiri.getText(), txtKecamatan.getText(),
                                txtNomorUkm.getText(), txtInfoUkm.getText(),
                                txtLokasiUkm.getText());

            mycode.tampilDataDaftarUkm(tabelUkm, "SELECT*FROM daftar_ukm");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhDaftarUkmActionPerformed

    private void btnSmpnDaftarUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnDaftarUkmActionPerformed
        try {
                if(txtIdUkm.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "ID UKM Belum Diisi");
                    txtIdUkm.requestFocus();
                } else if(txtNamaUkm.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nama UKM Belum Diisi");
                    txtNamaUkm.requestFocus();
                } else if(txtAlamatUkm.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                    txtAlamatUkm.requestFocus();
                } else if(txtJenisUsaha.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Jenis Usaha Belum Diisi");
                    txtJenisUsaha.requestFocus();
                } else if(txtTahunBerdiri.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Tahun Berdiri Belum Diisi");
                    txtTahunBerdiri.requestFocus();
                } else if(txtKecamatan.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Kecamatan Belum Diisi");
                    txtKecamatan.requestFocus();
                } else if(txtNomorUkm.getText().isEmpty()){ 
                    JOptionPane.showMessageDialog(null, "Nomor Belum Diisi");
                    txtNomorUkm.requestFocus();
                // Validasi txtGambarUkm DIHILANGKAN
                } else if(txtInfoUkm.getText().isEmpty()){ 
                    JOptionPane.showMessageDialog(null, "Info Belum Diisi");
                    txtInfoUkm.requestFocus();
                } else if(txtLokasiUkm.getText().isEmpty()){ 
                    JOptionPane.showMessageDialog(null, "Lokasi Belum Diisi");
                    txtLokasiUkm.requestFocus();
                } else {
                    mycode.simpanDaftarUkm02(txtIdUkm.getText(), txtNamaUkm.getText(),
                                            txtAlamatUkm.getText(), txtJenisUsaha.getText(),
                                            txtTahunBerdiri.getText(), txtKecamatan.getText(),
                                            txtNomorUkm.getText(), txtInfoUkm.getText(), 
                                            txtLokasiUkm.getText());

                    mycode.tampilDataDaftarUkm(tabelUkm, "SELECT*FROM daftar_ukm");

                    if (mycode.duplikasi == true){
                        txtNamaUkm.setText(mycode.CEK_NAMA_UKM);
                        txtAlamatUkm.setText(mycode.CEK_ALAMAT_UKM);
                        txtJenisUsaha.setText(mycode.CEK_JENIS_USAHA);
                        txtTahunBerdiri.setText(mycode.CEK_TAHUN_BERDIRI);
                        txtKecamatan.setText(mycode.CEK_KECAMATAN);
                        txtNomorUkm.setText(mycode.CEK_NOMOR);
                        txtInfoUkm.setText(mycode.CEK_INFO);
                        txtLokasiUkm.setText(mycode.CEK_LOKASI);
                    }
                }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_btnSmpnDaftarUkmActionPerformed

    private void btnHpsDaftarUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsDaftarUkmActionPerformed
        try {
            mycode.hapusDaftarUkm(txtIdUkm.getText());
            mycode.tampilDataDaftarUkm(tabelUkm, "SELECT*FROM daftar_ukm");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsDaftarUkmActionPerformed

    private void txtNamaUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaUkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaUkmActionPerformed

    private void txtIdUkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUkmActionPerformed

    private void txtNamaKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKegiatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKegiatanActionPerformed

    private void btnHpsKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKegiatanActionPerformed
        try {
            mycode.hapusKegiatan(txtIdKegiatan.getText());
            mycode.tampilDataKegiatan(tabelKegiatan, "SELECT*FROM kegiatan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKegiatanActionPerformed

    private void btnSmpnKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKegiatanActionPerformed
        try {
            if(txtIdKegiatan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Kegiatan Belum Diisi");
                txtIdKegiatan.requestFocus();
            } else if(txtNamaKegiatan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Kegiatan Belum Diisi");
                txtNamaKegiatan.requestFocus();
            } else if(txtTanggalKegiatan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Tanggal Belum Diisi");
                txtTanggalKegiatan.requestFocus();
            } else if(txtTempatKegiatan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Tempat Belum Diisi");
                txtTempatKegiatan.requestFocus();
            } else {
                mycode.simpanKegiatan02(txtIdKegiatan.getText(), txtNamaKegiatan.getText(),
                                        txtTanggalKegiatan.getText(), txtTempatKegiatan.getText());

                mycode.tampilDataKegiatan(tabelKegiatan, "SELECT*FROM kegiatan");

                if (mycode.duplikasi == true){
                    txtNamaKegiatan.setText(mycode.CEK_NAMA_KEGIATAN);
                    txtTanggalKegiatan.setText(mycode.CEK_TANGGAL_KEGIATAN);
                    txtTempatKegiatan.setText(mycode.CEK_TEMPAT_KEGIATAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKegiatanActionPerformed

    private void btnUbhKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKegiatanActionPerformed
        try {
            mycode.ubahKegiatan(txtIdKegiatan.getText(), txtNamaKegiatan.getText(),
                                txtTanggalKegiatan.getText(), txtTempatKegiatan.getText());

            mycode.tampilDataKegiatan(tabelKegiatan, "SELECT*FROM kegiatan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKegiatanActionPerformed

    private void txtCariKegiatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKegiatanKeyReleased
        String c = txtCariKegiatan.getText();
        String cari = "SELECT*FROM kegiatan WHERE id_kegiatan LIKE '%"+c+"%'"+
                      "OR nama_kegiatan LIKE '%"+c+"%' OR tanggal LIKE '%"+c+"%'"+
                      "OR tempat LIKE '%"+c+"%'";
        mycode.tampilDataKegiatan(tabelKegiatan, cari);
    }//GEN-LAST:event_txtCariKegiatanKeyReleased

    private void txtIdKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKegiatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKegiatanActionPerformed

    private void txtIdUkmKomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUkmKomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUkmKomenActionPerformed

    private void btnHpsKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKomentarActionPerformed
        try {
                mycode.hapusKomentar(txtIdKomen.getText());
                mycode.tampilDataKomentar(tabelKomentar, "SELECT*FROM komentar");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKomentarActionPerformed

    private void btnSmpnKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKomentarActionPerformed
        try {
            if(txtIdKomen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Komen Belum Diisi");
                txtIdKomen.requestFocus();
            } else if(txtIdUkmKomen.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID UKM Belum Diisi");
                txtIdUkmKomen.requestFocus();
            } else if(txtReplyFrom.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Reply From Belum Diisi");
                txtReplyFrom.requestFocus();
            } else if(txtNamaKomen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Komen Belum Diisi");
                txtNamaKomen.requestFocus();
            } else if(txtEmailKomen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Email Komen Belum Diisi");
                txtEmailKomen.requestFocus();
            } else if(txtIsiKomen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Isi Komen Belum Diisi");
                txtIsiKomen.requestFocus();
            } else if(txtTanggalKomen.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Tanggal Belum Diisi");
                txtTanggalKomen.requestFocus();
            } else {
                mycode.simpanKomentar02(txtIdKomen.getText(), txtIdUkmKomen.getText(),
                                        txtReplyFrom.getText(), txtNamaKomen.getText(),
                                        txtEmailKomen.getText(), txtIsiKomen.getText(),
                                        txtTanggalKomen.getText());

                mycode.tampilDataKomentar(tabelKomentar, "SELECT*FROM komentar");

                if (mycode.duplikasi == true){
                    txtIdUkmKomen.setText(mycode.CEK_ID_UKM_KOMEN);
                    txtReplyFrom.setText(mycode.CEK_REPLY_FROM);
                    txtNamaKomen.setText(mycode.CEK_NAMA_KOMEN);
                    txtEmailKomen.setText(mycode.CEK_EMAIL_KOMEN);
                    txtIsiKomen.setText(mycode.CEK_ISI_KOMEN);
                    txtTanggalKomen.setText(mycode.CEK_TANGGAL_KOMEN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKomentarActionPerformed

    private void btnUbhKomentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKomentarActionPerformed
        try {
            mycode.ubahKomentar(txtIdKomen.getText(), txtIdUkmKomen.getText(),
                                txtReplyFrom.getText(), txtNamaKomen.getText(),
                                txtEmailKomen.getText(), txtIsiKomen.getText(),
                                txtTanggalKomen.getText());

            mycode.tampilDataKomentar(tabelKomentar, "SELECT*FROM komentar");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKomentarActionPerformed

    private void txtCariKomentarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKomentarKeyReleased
        String c = txtCariKomentar.getText();
        String cari = "SELECT*FROM komentar WHERE id_komen LIKE '%"+c+"%'"+
                      "OR id_ukm LIKE '%"+c+"%' OR reply_from LIKE '%"+c+"%'"+
                      "OR nama_komen LIKE '%"+c+"%' OR email_komen LIKE '%"+c+"%'"+
                      "OR tanggal LIKE '%"+c+"%'";
        mycode.tampilDataKomentar(tabelKomentar, cari);
    }//GEN-LAST:event_txtCariKomentarKeyReleased

    private void txtIdKomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKomenActionPerformed

    private void txtNamaPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPengurusActionPerformed

    private void btnHpsPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPengurusActionPerformed
        try {
            mycode.hapusPengurus(txtIdPengurus.getText());
            mycode.tampilDataPengurus(tabelPengurus, "SELECT*FROM pengurus");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPengurusActionPerformed

    private void btnSmpnPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPengurusActionPerformed
        try {
            if(txtIdPengurus.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pengurus Belum Diisi");
                txtIdPengurus.requestFocus();
            } else if(txtNamaPengurus.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Pengurus Belum Diisi");
                txtNamaPengurus.requestFocus();
            } else if(txtJabatan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jabatan Belum Diisi");
                txtJabatan.requestFocus();
            } else {
                mycode.simpanPengurus02(txtIdPengurus.getText(), txtNamaPengurus.getText(),
                                        txtJabatan.getText());

                mycode.tampilDataPengurus(tabelPengurus, "SELECT*FROM pengurus");

                if (mycode.duplikasi == true){
                    txtNamaPengurus.setText(mycode.CEK_NAMA_PENGURUS);
                    txtJabatan.setText(mycode.CEK_JABATAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPengurusActionPerformed

    private void btnUbhPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPengurusActionPerformed
        try {
                mycode.ubahPengurus(txtIdPengurus.getText(), txtNamaPengurus.getText(),
                                    txtJabatan.getText());

                mycode.tampilDataPengurus(tabelPengurus, "SELECT*FROM pengurus");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPengurusActionPerformed

    private void txtCariPengurusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPengurusKeyReleased
        String c = txtCariPengurus.getText();
        String cari = "SELECT*FROM pengurus WHERE id_pengurus LIKE '%"+c+"%'"+
                      "OR nama_pengurus LIKE '%"+c+"%' OR jabatan LIKE '%"+c+"%'";
        mycode.tampilDataPengurus(tabelPengurus, cari);
    }//GEN-LAST:event_txtCariPengurusKeyReleased

    private void txtIdPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPengurusActionPerformed

    private void btnPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengurusActionPerformed
        Content.removeAll(); 
        Content.add(pnlPengurus);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPengurusActionPerformed

    private void txtIdUkmProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUkmProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUkmProdukActionPerformed

    private void btnHpsProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsProdukActionPerformed
        try {
            mycode.hapusDaftarProduk(txtIdProduk.getText());
            mycode.tampilDataDaftarProduk(tabelDaftarProduk, "SELECT*FROM daftar_produk");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsProdukActionPerformed

    private void btnSmpnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnProdukActionPerformed
        try {
            if(txtIdProduk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Produk Belum Diisi");
                txtIdProduk.requestFocus();
            } else if(txtIdUkmProduk.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID UKM Belum Diisi");
                txtIdUkmProduk.requestFocus();
            } else if(txtNamaProduk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Produk Belum Diisi");
                txtNamaProduk.requestFocus();
            } else {
                mycode.simpanDaftarProduk02(txtIdProduk.getText(), txtIdUkmProduk.getText(),
                                            txtNamaProduk.getText());

                mycode.tampilDataDaftarProduk(tabelDaftarProduk, "SELECT*FROM daftar_produk");

                if (mycode.duplikasi == true){
                    txtIdUkmProduk.setText(mycode.CEK_ID_UKM_PRODUK);
                    txtNamaProduk.setText(mycode.CEK_NAMA_PRODUK);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnProdukActionPerformed

    private void btnUbhProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhProdukActionPerformed
        try {
            mycode.ubahDaftarProduk(txtIdProduk.getText(), txtIdUkmProduk.getText(),
                                    txtNamaProduk.getText());

            mycode.tampilDataDaftarProduk(tabelDaftarProduk, "SELECT*FROM daftar_produk");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhProdukActionPerformed

    private void txtCariDaftarProdukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDaftarProdukKeyReleased
        String c = txtCariDaftarProduk.getText();
        String cari = "SELECT*FROM daftar_produk WHERE id_produk LIKE '%"+c+"%'"+
                      "OR id_ukm LIKE '%"+c+"%' OR nama_produk LIKE '%"+c+"%'";
        mycode.tampilDataDaftarProduk(tabelDaftarProduk, cari);
    }//GEN-LAST:event_txtCariDaftarProdukKeyReleased

    private void txtIdProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdukActionPerformed

    private void txtKecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKecamatanActionPerformed

    private void txtTahunBerdiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunBerdiriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunBerdiriActionPerformed

    private void txtEmailKomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailKomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKomenActionPerformed

    private void txtNamaKomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKomenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsDaftarUkm;
    private javax.swing.JButton btnHpsKegiatan;
    private javax.swing.JButton btnHpsKomentar;
    private javax.swing.JButton btnHpsPengurus;
    private javax.swing.JButton btnHpsProduk;
    private javax.swing.JButton btnKegiatan;
    private javax.swing.JButton btnKomentar;
    private javax.swing.JButton btnPengurus;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnSmpnDaftarUkm;
    private javax.swing.JButton btnSmpnKegiatan;
    private javax.swing.JButton btnSmpnKomentar;
    private javax.swing.JButton btnSmpnPengurus;
    private javax.swing.JButton btnSmpnProduk;
    private javax.swing.JButton btnUbhDaftarUkm;
    private javax.swing.JButton btnUbhKegiatan;
    private javax.swing.JButton btnUbhKomentar;
    private javax.swing.JButton btnUbhPengurus;
    private javax.swing.JButton btnUbhProduk;
    private javax.swing.JButton btnUkm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKegiatan;
    private javax.swing.JPanel pnlKomentar;
    private javax.swing.JPanel pnlPengurus;
    private javax.swing.JPanel pnlProduk;
    private javax.swing.JPanel pnlUkm;
    private javax.swing.JTable tabelDaftarProduk;
    private javax.swing.JTable tabelKegiatan;
    private javax.swing.JTable tabelKomentar;
    private javax.swing.JTable tabelPengurus;
    private javax.swing.JTable tabelUkm;
    private javax.swing.JTextField txtAlamatUkm;
    private javax.swing.JTextField txtCariDaftarProduk;
    private javax.swing.JTextField txtCariDaftarUkm;
    private javax.swing.JTextField txtCariKegiatan;
    private javax.swing.JTextField txtCariKomentar;
    private javax.swing.JTextField txtCariPengurus;
    private javax.swing.JTextField txtEmailKomen;
    private javax.swing.JTextField txtIdKegiatan;
    private javax.swing.JTextField txtIdKomen;
    private javax.swing.JTextField txtIdPengurus;
    private javax.swing.JTextField txtIdProduk;
    private javax.swing.JTextField txtIdUkm;
    private javax.swing.JTextField txtIdUkmKomen;
    private javax.swing.JTextField txtIdUkmProduk;
    private javax.swing.JTextField txtInfoUkm;
    private javax.swing.JTextField txtIsiKomen;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtJenisUsaha;
    private javax.swing.JTextField txtKecamatan;
    private javax.swing.JTextField txtLokasiUkm;
    private javax.swing.JTextField txtNamaKegiatan;
    private javax.swing.JTextField txtNamaKomen;
    private javax.swing.JTextField txtNamaPengurus;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtNamaUkm;
    private javax.swing.JTextField txtNomorUkm;
    private javax.swing.JTextField txtReplyFrom;
    private javax.swing.JTextField txtTahunBerdiri;
    private javax.swing.JTextField txtTanggalKegiatan;
    private javax.swing.JTextField txtTanggalKomen;
    private javax.swing.JTextField txtTempatKegiatan;
    // End of variables declaration//GEN-END:variables
}
